openapi: 3.0.0
info:
  title: Food Delivery API
  description: REST API for food delivery app
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /calculate-price:
    post:
      summary: Calculate delivery price
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                zone:
                  type: string
                organization_id:
                  type: string
                total_distance:
                  type: number
                item_type:
                  type: string
                  enum: [perishable, non-perishable]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_price:
                    type: number
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
